# Build Stage
FROM golang:1.19.4-alpine3.17 as build

WORKDIR /go/src/app

## Dependencies
COPY go.mod go.sum .
RUN go mod download

## Source code
COPY cmd cmd
COPY main.go .

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o /go/bin/audiotheker -ldflags="-s -w" main.go

# Run Stage
FROM gcr.io/distroless/static-debian11:nonroot

COPY --from=build --chown=nonroot:nonroot /go/bin/audiotheker /
ENTRYPOINT ["/audiotheker"]